aspnet-core/src/WorkflowCoreDockingDemo.Web.Mvc/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;
using Abp.AspNetCore.Mvc.Authorization;
using WorkflowCoreDockingDemo.Controllers;

namespace WorkflowCoreDockingDemo.Web.Controllers
{
    [AbpMvcAuthorize]
    public class AboutController : WorkflowCoreDockingDemoControllerBase
    {
        public ActionResult Index()
        {
            return View();
        }
	}
}

aspnet-core/src/WorkflowCoreDockingDemo.Web.Mvc/Views/Shared/Components/AccountLanguages/AccountLanguagesViewComponent.cs
using System.Linq;
using System.Threading.Tasks;
using Abp.Localization;
using Microsoft.AspNetCore.Mvc;

namespace WorkflowCoreDockingDemo.Web.Views.Shared.Components.AccountLanguages
{
    public class AccountLanguagesViewComponent : WorkflowCoreDockingDemoViewComponent
    {
        private readonly ILanguageManager _languageManager;

        public AccountLanguagesViewComponent(ILanguageManager languageManager)
        {
            _languageManager = languageManager;
        }

        public Task<IViewComponentResult> InvokeAsync()
        {
            var model = new LanguageSelectionViewModel
            {
                CurrentLanguage = _languageManager.CurrentLanguage,
                Languages = _languageManager.GetLanguages().Where(l => !l.IsDisabled).ToList()
                .Where(l => !l.IsDisabled)
                .ToList(),
                CurrentUrl = Request.Path
            };

            return Task.FromResult(View(model) as IViewComponentResult);
        }
    }
}

aspnet-core/src/WorkflowCoreDockingDemo.Web.Mvc/Views/Shared/Components/RightNavbarLanguageSwitch/RightNavbarLanguageSwitchViewComponent.cs
using System.Linq;
using Abp.Localization;
using Microsoft.AspNetCore.Mvc;

namespace WorkflowCoreDockingDemo.Web.Views.Shared.Components.RightNavbarLanguageSwitch
{
    public class RightNavbarLanguageSwitchViewComponent : WorkflowCoreDockingDemoViewComponent
    {
        private readonly ILanguageManager _languageManager;

        public RightNavbarLanguageSwitchViewComponent(ILanguageManager languageManager)
        {
            _languageManager = languageManager;
        }

        public IViewComponentResult Invoke()
        {
            var model = new RightNavbarLanguageSwitchViewModel
            {
                CurrentLanguage = _languageManager.CurrentLanguage,
                Languages = _languageManager.GetLanguages().Where(l => !l.IsDisabled).ToList()
            };

            return View(model);
        }
    }
}

aspnet-core/src/WorkflowCoreDockingDemo.Web.Mvc/Views/Shared/Components/RightNavbarUserArea/RightNavbarUserAreaViewComponent.cs
using System.Threading.Tasks;
using Abp.Configuration.Startup;
using WorkflowCoreDockingDemo.Sessions;
using Microsoft.AspNetCore.Mvc;

namespace WorkflowCoreDockingDemo.Web.Views.Shared.Components.RightNavbarUserArea
{
    public class RightNavbarUserAreaViewComponent : WorkflowCoreDockingDemoViewComponent
    {
        private readonly ISessionAppService _sessionAppService;
        private readonly IMultiTenancyConfig _multiTenancyConfig;

        public RightNavbarUserAreaViewComponent(
            ISessionAppService sessionAppService,
            IMultiTenancyConfig multiTenancyConfig)
        {
            _sessionAppService = sessionAppService;
            _multiTenancyConfig = multiTenancyConfig;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var model = new RightNavbarUserAreaViewModel
            {
                LoginInformations = await _sessionAppService.GetCurrentLoginInformations(),
                IsMultiTenancyEnabled = _multiTenancyConfig.IsEnabled,
            };

            return View(model);
        }
    }
}

aspnet-core/src/WorkflowCoreDockingDemo.Web.Mvc/Views/Shared/Components/SideBarMenu/SideBarMenuViewComponent.cs
using System.Threading.Tasks;
using Abp.Application.Navigation;
using Abp.Runtime.Session;
using Microsoft.AspNetCore.Mvc;

namespace WorkflowCoreDockingDemo.Web.Views.Shared.Components.SideBarMenu
{
    public class SideBarMenuViewComponent : WorkflowCoreDockingDemoViewComponent
    {
        private readonly IUserNavigationManager _userNavigationManager;
        private readonly IAbpSession _abpSession;

        public SideBarMenuViewComponent(
            IUserNavigationManager userNavigationManager,
            IAbpSession abpSession)
        {
            _userNavigationManager = userNavigationManager;
            _abpSession = abpSession;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var model = new SideBarMenuViewModel
            {
                MainMenu = await _userNavigationManager.GetMenuAsync("MainMenu", _abpSession.ToUserIdentifier())
            };

            return View(model);
        }
    }
}

aspnet-core/src/WorkflowCoreDockingDemo.Web.Mvc/Views/Shared/Components/SideBarUserArea/SideBarUserAreaViewComponent.cs
using System.Threading.Tasks;
using Abp.Configuration.Startup;
using WorkflowCoreDockingDemo.Sessions;
using Microsoft.AspNetCore.Mvc;

namespace WorkflowCoreDockingDemo.Web.Views.Shared.Components.SideBarUserArea
{
    public class SideBarUserAreaViewComponent : WorkflowCoreDockingDemoViewComponent
    {
        private readonly ISessionAppService _sessionAppService;
        private readonly IMultiTenancyConfig _multiTenancyConfig;

        public SideBarUserAreaViewComponent(
            ISessionAppService sessionAppService,
            IMultiTenancyConfig multiTenancyConfig)
        {
            _sessionAppService = sessionAppService;
            _multiTenancyConfig = multiTenancyConfig;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var model = new SideBarUserAreaViewModel
            {
                LoginInformations = await _sessionAppService.GetCurrentLoginInformations(),
                IsMultiTenancyEnabled = _multiTenancyConfig.IsEnabled,
            };

            return View(model);
        }
    }
}

aspnet-core/src/WorkflowCoreDockingDemo.Web.Mvc/Views/Shared/Components/TenantChange/TenantChangeViewComponent.cs
using System.Threading.Tasks;
using Abp.ObjectMapping;
using WorkflowCoreDockingDemo.Sessions;
using Microsoft.AspNetCore.Mvc;

namespace WorkflowCoreDockingDemo.Web.Views.Shared.Components.TenantChange
{
    public class TenantChangeViewComponent : WorkflowCoreDockingDemoViewComponent
    {
        private readonly ISessionAppService _sessionAppService;
        private readonly IObjectMapper _objectMapper;

        public TenantChangeViewComponent(ISessionAppService sessionAppService, IObjectMapper objectMapper)
        {
            _sessionAppService = sessionAppService;
            _objectMapper = objectMapper;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var loginInfo = await _sessionAppService.GetCurrentLoginInformations();
            var model = _objectMapper.Map<TenantChangeViewModel>(loginInfo);
            return View(model);
        }
    }
}

aspnet-core/src/WorkflowCoreDockingDemo.Web.Mvc/Views/Shared/Layout/_Alerts.cshtml
@using Abp.Web.Mvc.Alerts

@inject IAlertManager AlertManager

@if (AlertManager.Alerts.Any())
{
    <div class="container-fluid">
        @foreach (var alert in AlertManager.Alerts)
        {
            var alertClass = "alert-";
            var iconClass = "fa-";
            switch (alert.Type)
            {
                case AlertType.Success:
                    alertClass += "success";
                    iconClass += "check";
                    break;
                case AlertType.Danger:
                    alertClass += "danger";
                    iconClass += "ban";
                    break;
                case AlertType.Warning:
                    alertClass += "warning";
                    iconClass += "exclamation-triangle";
                    break;
                case AlertType.Info:
                    alertClass += "info";
                    iconClass += "info";
                    break;
            }

            <div class="alert @alertClass @(alert.Dismissible ? "alert-dismisable" : "") mt-3 mr-1 ml-1">
                @if (alert.Dismissible)
                {
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                }
                <h5>
                    <i class="icon fas @iconClass"></i>
                    @alert.Title
                </h5>
                @alert.Text
            </div>
        }
    </div>
}

aspnet-core/src/WorkflowCoreDockingDemo.Web.Mvc/Views/Shared/Layout/_Footer.cshtml
@using WorkflowCoreDockingDemo
<footer class="main-footer">
    <strong>Copyright &copy; @DateTime.Now.Year <a href="javascript:void(0);">WorkflowCoreDockingDemo</a>.</strong> All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
        <b>@L("Version")</b> @AppVersionHelper.Version [@AppVersionHelper.ReleaseDate.ToString("yyyyMMdd")]
    </div>
</footer>

aspnet-core/src/WorkflowCoreDockingDemo.Web.Mvc/Views/Shared/Layout/_Header.LeftNavbar.cshtml
<ul class="navbar-nav">
    <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="javascript:;"><i class="fas fa-bars"></i></a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
        <a class="nav-link" asp-controller="Home" asp-action="Index">@L("HomePage")</a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
        <a class="nav-link" asp-controller="About" asp-action="Index">@L("About")</a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
        <a class="nav-link" id="workflowcenter" href="javascript:gotoWorkflowCenter()">流程中心</a>
    </li>
</ul>

<script>
    function parseCookie(cookie) {
        var cookieObj = {};
        var cookies = cookie.split(';');

        for (var i = 0; i < cookies.length; i++) {
            var cookieParts = cookies[i].split('=');
            var cookieName = cookieParts[0].trim();
            var cookieValue = cookieParts[1];

            // 将 cookie 值进行解码
            cookieValue = decodeURIComponent(cookieValue);

            // 将 cookie 名称和值存储到对象中
            cookieObj[cookieName] = cookieValue;
        }

        return cookieObj;
    }

    function gotoWorkflowCenter() {
        var token = parseCookie(document.cookie)['Abp.AuthToken'];
        window.open('http://localhost:9528/#/login?access_token=' + encodeURI('Abp.AuthToken=' + token), "_bank");
        //window.open('http://localhost:9528/#/login?access_token=' + token, "_bank");
    }

</script>

aspnet-core/src/WorkflowCoreDockingDemo.Web.Mvc/Views/Shared/Layout/_Header.RightNavbar.cshtml
@using WorkflowCoreDockingDemo.Web.Views.Shared.Components.RightNavbarLanguageSwitch
@using WorkflowCoreDockingDemo.Web.Views.Shared.Components.RightNavbarUserArea
<ul class="navbar-nav ml-auto">
    @await Component.InvokeAsync(typeof(RightNavbarLanguageSwitchViewComponent))
    @await Component.InvokeAsync(typeof(RightNavbarUserAreaViewComponent))
</ul>

aspnet-core/src/WorkflowCoreDockingDemo.Web.Mvc/Views/Shared/Layout/_Header.cshtml
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    @await Html.PartialAsync("_Header.LeftNavbar.cshtml")
    @await Html.PartialAsync("_Header.RightNavbar.cshtml")
</nav>

aspnet-core/src/WorkflowCoreDockingDemo.Web.Mvc/Views/Shared/Layout/_Layout.cshtml
@using Abp.Configuration.Startup
@using Abp.Web.Mvc.Alerts
@using Abp.Web.Security.AntiForgery
@using WorkflowCoreDockingDemo.Web.Resources
@inject IAbpAntiForgeryManager AbpAntiForgeryManager
@inject IMultiTenancyConfig MultiTenancyConfig
@inject IWebResourceManager WebResourceManager
@inject IAlertManager AlertManager
@inject ILanguageManager LanguageManager
@{
    AbpAntiForgeryManager.SetCookie(Context);

    var pageTitle = !string.IsNullOrWhiteSpace(ViewBag.Title) ? ViewBag.Title + " / " : "";
    pageTitle += "WorkflowCoreDockingDemo";
}
<!DOCTYPE html>
<html lang="@LanguageManager.CurrentLanguage.Name">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <title>@pageTitle</title>

    @await Html.PartialAsync("_Styles.cshtml")
    @RenderSection("styles", required: false)
</head>
<body class="hold-transition sidebar-mini">
    <div class="wrapper">
        @await Html.PartialAsync("_Header.cshtml")
        @await Html.PartialAsync("_SideBar.cshtml")
        <div class="content-wrapper">
            @await Html.PartialAsync("_Alerts.cshtml")
            @RenderBody()
        </div>
        @await Html.PartialAsync("_Footer.cshtml")
    </div>

    @await Html.PartialAsync("_Scripts.cshtml")
    @RenderSection("scripts", required: false)
    @WebResourceManager.RenderScripts()
</body>
</html>

aspnet-core/src/WorkflowCoreDockingDemo.Web.Mvc/Views/Shared/Layout/_Scripts.cshtml
@using System.Globalization
@using Abp.AspNetCore.Mvc.Caching
@using Abp.CachedUniqueKeys
@inject WorkflowCoreDockingDemo.Timing.AppTimes AppTimes
@inject ICachedUniqueKeyPerUser CachedUniqueKeyPerUser
@inject IGetScriptsResponsePerUserConfiguration GetScriptsResponsePerUserConfiguration

<environment names="Development">
    @*core scripts start*@
    <script src="~/libs/jquery/jquery.js" asp-append-version="true"></script>
    @*core scripts end*@

    @*admin-lte scripts start*@
    <script src="~/libs/bootstrap/dist/js/bootstrap.bundle.js" asp-append-version="true"></script>
    <script src="~/libs/datatables/js/jquery.dataTables.min.js" asp-append-version="true"></script>
    <script src="~/view-resources/Views/_Bundles/helpers.min.js" asp-append-version="true"></script>
    <script src="~/view-resources/Views/_Bundles/datatables.ajax.min.js" asp-append-version="true"></script>
    <script src="~/libs/datatables/js/dataTables.bootstrap4.min.js" asp-append-version="true"></script>
    <script src="~/libs/datatables/js/dataTables.responsive.min.js" asp-append-version="true"></script>
    <script src="~/libs/datatables/js/responsive.bootstrap4.min.js" asp-append-version="true"></script>
    <script src="~/libs/datatables/js/dataTables.buttons.js" asp-append-version="true"></script>
    <script src="~/libs/datatables/js/buttons.bootstrap4.js" asp-append-version="true"></script>
    <script src="~/libs/admin-lte/dist/js/adminlte.js" asp-append-version="true"></script>
    @*admin-lte scripts end*@

    @*abp scripts start*@
    <script src="~/libs/block-ui/jquery.blockUI.js" asp-append-version="true"></script>
    <script src="~/libs/spin/spin.js" asp-append-version="true"></script>
    <script src="~/libs-ext/spin/jquery.spin.js" asp-append-version="true"></script>
    <script src="~/libs/sweetalert/sweetalert.min.js" asp-append-version="true"></script>
    <script src="~/libs/toastr/toastr.min.js" asp-append-version="true"></script>
    <script src="~/libs/moment/moment-with-locales.js" asp-append-version="true"></script>
    <script src="~/libs/signalr/dist/browser/signalr.js" asp-append-version="true"></script>
    <script src="~/libs/abp-web-resources/Abp/Framework/scripts/abp.js" asp-append-version="true"></script>
    <script src="~/libs/abp-web-resources/Abp/Framework/scripts/libs/abp.jquery.js" asp-append-version="true"></script>
    <script src="~/libs/abp-web-resources/Abp/Framework/scripts/libs/abp.toastr.js" asp-append-version="true"></script>
    <script src="~/libs/abp-web-resources/Abp/Framework/scripts/libs/abp.blockUI.js" asp-append-version="true"></script>
    <script src="~/libs/abp-web-resources/Abp/Framework/scripts/libs/abp.spin.js" asp-append-version="true"></script>
    <script src="~/libs/abp-web-resources/Abp/Framework/scripts/libs/abp.sweet-alert.js" asp-append-version="true"></script>
    <script src="~/libs/abp-web-resources/Abp/Framework/scripts/libs/abp.signalr-client.js" asp-append-version="true"></script>
    @*abp scripts end*@

    @*other scripts start*@
    <script src="~/libs/jquery-validate/jquery.validate.js" asp-append-version="true"></script>
    <script src="~/libs/jquery-validate/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
    <script src="~/libs/push.js/push.js" asp-append-version="true"></script>
    @*other scripts end*@

    @*custom scripts start*@
    <script src="~/js/abp.dataTable.js" asp-append-version="true"></script>
    <script src="~/js/main.js" asp-append-version="true"></script>
    @*custom scripts end*@
    
    <script type="text/javascript">
        // This is used to get the application's root path from javascript.
        // It's useful if you're running application in a virtual directory under IIS.
        var abp = abp || {};
        abp.appPath = '@ApplicationPath';
    </script>
</environment>

<environment names="Staging,Production">
    <script src="~/view-resources/Views/_Bundles/shared-layout.min.js" asp-append-version="true"></script>
    <script type="text/javascript">
        // This is used to get the application's root path from javascript.
        // It's useful if you're running application in a virtual directory under IIS.
        var abp = abp || {};
        abp.appPath = '@ApplicationPath';
    </script>
</environment>

@if (CultureInfo.CurrentUICulture.Name != "en")
{
    var normalizedCurrentUICultureName = CultureInfo.CurrentUICulture.Name.Replace("-", "_");
    var localizationFileNameWithExtension = "messages_";
    switch (normalizedCurrentUICultureName)
    {
        case "zh_Hans":
            localizationFileNameWithExtension += "zh";
            break;
        case "es_MX":
            localizationFileNameWithExtension += "es";
            break;
        default:
            localizationFileNameWithExtension += normalizedCurrentUICultureName;
            break;
    }
    localizationFileNameWithExtension += ".min.js";
    <script src="~/libs/jquery-validate/localization/@localizationFileNameWithExtension" asp-append-version="true"></script>
}

<script type="text/javascript">
        // Localizing momentjs
        moment.locale('@CultureInfo.CurrentUICulture.Name');
</script>

<!-- Dynamic scripts of ABP system (They are created on runtime and can not be bundled) -->
<script src="~/AbpServiceProxies/GetAll?v=@(AppTimes.StartupTime.Ticks)" type="text/javascript"></script>

@if (GetScriptsResponsePerUserConfiguration.IsEnabled)
{
    <script src="@(ApplicationPath)AbpScripts/GetScripts?v=@(await CachedUniqueKeyPerUser.GetKeyAsync(GetScriptsResponsePerUserCache.CacheName))" type="text/javascript"></script>
}
else
{
    <script src="@(ApplicationPath)AbpScripts/GetScripts?v=@(AppTimes.StartupTime.Ticks)" type="text/javascript"></script>
}

aspnet-core/src/WorkflowCoreDockingDemo.Web.Mvc/Views/Shared/Layout/_SideBar.Logo.cshtml
<a class="brand-link" asp-controller="Home" asp-action="Index">
    <img src="~/img/logo.png" alt="Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
    <span class="brand-text font-weight-light">WorkflowCoreDockingDemo</span>
</a>

aspnet-core/src/WorkflowCoreDockingDemo.Web.Mvc/Views/Shared/Layout/_SideBar.cshtml
@using WorkflowCoreDockingDemo.Web.Views.Shared.Components.SideBarMenu
@using WorkflowCoreDockingDemo.Web.Views.Shared.Components.SideBarUserArea
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    @await Html.PartialAsync("_SideBar.Logo.cshtml")
    <div class="sidebar">
        @await Component.InvokeAsync(typeof(SideBarUserAreaViewComponent))
        @await Component.InvokeAsync(typeof(SideBarMenuViewComponent))
    </div>
</aside>

aspnet-core/src/WorkflowCoreDockingDemo.Web.Mvc/Views/Shared/Layout/_Styles.cshtml
<link rel="shortcut icon" href="~/img/favicon.ico">
<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

<environment names="Development">
    @*admin-lte styles start*@
    <link href="~/libs/font-awesome/css/all.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/libs/icheck-bootstrap/icheck-bootstrap.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/libs/datatables/css/dataTables.bootstrap4.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/libs/datatables/css/responsive.bootstrap4.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/libs/datatables/css/buttons.bootstrap4.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/libs/admin-lte/dist/css/adminlte.min.css" rel="stylesheet" asp-append-version="true" />
    @*admin-lte styles end*@

    @*abp styles start*@
    <link href="~/libs/toastr/toastr.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/libs-ext/famfamfam-flags/dist/sprite/famfamfam-flags.min.css" rel="stylesheet" asp-append-version="true" />
    @*abp styles end*@

    @*custom styles start*@
    <link href="~/view-resources/Views/Shared/_Layout.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/style.css" rel="stylesheet" asp-append-version="true" />
    @*custom styles end*@
</environment>

<environment names="Staging,Production">
    <link href="~/view-resources/Views/_Bundles/shared-layout.min.css" rel="stylesheet" asp-append-version="true" />
</environment>